### ISSUE TITLE
Lag making game unplayable

### ISSUE THREAD

**Issue by Presyon** [BlakeBr0/ExtendedCrafting#138] opened 2021-10-18 19:47 UTC
Everything you need to know is here since I was told it was Mekanism before they figured out it was Extended Crafting

https://github.com/mekanism/Mekanism/issues/7326

**Comment by Presyon** [comment] 2021-10-19 01:52
Side note: This problem is caused by me making an auto input system to put items into pedestals I think. I believe this since the pipes are included to produce lag in the spark report.

**Comment by BlakeBr0** [comment] 2021-10-29 20:09
Can you show me the recipe you were trying to make?

**Comment by Presyon** [comment] 2021-10-30 04:57
![2021-10-29_23 56 19](https://user-images.githubusercontent.com/76184727/139520775-3a4afb2b-9d06-4db8-bdc9-5d6b7c7d5fe9.png)

**Comment by BlakeBr0** [comment] 2021-10-30 07:25
So if you were to setup this in a different world can you reproduce it? According to that profile it gets stuck doing recipe matching, which is weird. Maybe there's a mod that modifies how forges shapeless recipe matcher works?

**Comment by Presyon** [comment] 2021-10-30 09:55
I'm not sure why it was doing that. I had to completely uninstall the mod, load up the world, then load up again with the mod installed for my frames to come back. After playing for 10+ hours after doing that its been fine so far so it is up to you whether you want to close this issue.

**Comment by Khazadir** [comment] 2021-11-20 00:54
I don't have the detailed data, but I also have this exact problem with this exact recipe.  From the other data shown, and the fact that this is a really specific recipe, I believe I am running the same modpack as the original poster.  Just wanted to add more data that this is not an isolated incident.

**Comment by Khazadir** [comment] 2021-11-27 15:31
I have an update.  I fixed the problem on my system by taking an item out of the crafting setup.

Later, I had lag recur and that's when I think the actual cause occurred to me.

I believe that this massive lag problem occurs when, based on the items put on the pedestals for the combination crafting, there is _no_ viable crafting recipe, it just starts looping through all the recipes and basically locks the system up almost completely as it's 'desperately' trying to figure out what you're doing.

To be specific, in the second case of lag going berserk, I had accidentally put my wireless crafting grid from refined storage on one of the pedestals...  In the first case, I had put down 5 of one of the items instead of 4.

Just my two cents...

**Comment by BlakeBr0** [comment] 2021-11-27 17:47
That's a good point. I'm going to change the crafting core to only look for recipes when items change, which should improve performance quite a bit. I'm not sure if that'll fix this exact issue though (since I could never reproduce it).

**Comment by BlakeBr0** [comment] 2021-11-28 06:45
I'm not 100% sure but this may be fixed in 3.1.10.

**Comment by BlakeBr0** [comment] 2021-12-31 05:53
I'm going to assume this is fixed. If not, feel free to reply here.

**Closed as completed by BlakeBr0** 2021-12-31 05:53 UTC
Labels: Bug, 1.16
