### ISSUE TITLE
[1.16.5] Container workbench dupe

### ISSUE THREAD

**Issue by bigenergy** [BlakeBr0/ExtendedCrafting#150] opened 2022-03-30 21:00 UTC
**Describe the bug**
each time taking the results of crafting through the shift, doubles the amount or puts more

**To Reproduce**
Steps to reproduce the behavior: see video

**Screenshots / Scripts / Logs**
https://www.youtube.com/watch?v=te5M6sY3-AQ

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.22
 - Cucumber: 4.1.12
 - Extended Crafting: 3.1.11
 - CraftTweaker (if applicable): no

**Comment by BlakeBr0** [comment] 2022-10-02 17:49
I'm not able to reproduce this. Is this still an issue on latest release?

**Comment by bigenergy** [comment] 2022-10-02 18:12
> I'm not able to reproduce this. Is this still an issue on latest release?

Yes

**Comment by BlakeBr0** [comment] 2023-03-09 22:44
I'm going to close this under the suspicion that there's an odd interaction happening involving your specific mod list. It doesn't seem like anyone else has reported this issue so I don't believe there's anything else I can do.

**Closed as completed by BlakeBr0** 2023-03-09 22:44 UTC
Labels: Bug

**Comment by bigenergy** [comment] 2025-02-04 17:00
@BlakeBr0 this problem still exists in the latest version of the mod on 1.20.1

**Comment by bigenergy** [comment] 2025-02-04 17:02
and also, if two players open the GUI, the result of the craft can be taken by 2 players

you need to prohibit the opening of the GUI if it is already open for another player
