### ISSUE TITLE
Automation Interface Doesn't Extract Output

### ISSUE THREAD

**Issue by NillerMedDild** [BlakeBr0/ExtendedCrafting#53] opened 2018-10-19 21:26 UTC
Hey, one of my users just reported an issue with the Automation Interface; here it is:
Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/336

## Issue Description

I use the automation interface from extended crafting to automate the different crafting table. I have an issue for output the item from the table.
The output item goes to the good slot in the crafting table, but the interface never pull it back. But when I open the crafting table the craft item go directly to the interface like its supposed to do.
I make a lot of tests, but I can't find a way to automatically pull out item from the different crafting table to the interface.

### Mod version
1.12.2-1.5.0

**Comment by Rodg88** [comment] 2018-11-15 07:42
I've had the same problem, with at least the first 3 tiers of crafting table
  
To reproduce, place a basic crafting table, with an automation interface on top. Set the recipe to the advanced crafting table, and save it to the interface:
![2018-11-15_18 35 23](https://user-images.githubusercontent.com/2611674/48537511-ecb20c80-e905-11e8-864d-d8730bd672ba.png)
![2018-11-15_18 35 27](https://user-images.githubusercontent.com/2611674/48537512-ecb20c80-e905-11e8-8fb6-e147caf11550.png)

Insert the required items into the interface input slot. Then nothing happens, no crafting result in the interface.
![2018-11-15_18 35 33](https://user-images.githubusercontent.com/2611674/48537515-ed4aa300-e905-11e8-9d9e-91046abe1724.png)

Then open the UI of the crafting table and the recipe will be in place for a tick, before it outputs the result to the interface as expected.
![2018-11-15_18 35 49](https://user-images.githubusercontent.com/2611674/48537516-ed4aa300-e905-11e8-8e10-db01dee710de.png)
![2018-11-15_18 35 51](https://user-images.githubusercontent.com/2611674/48537517-ed4aa300-e905-11e8-8077-561fd7b90697.png)

**Comment by amellors** [comment] 2018-11-28 15:52
I'm seeing this issue as well.

**Comment by Cr4zyy** [comment] 2018-12-01 09:44
Same issue, inserts items into tables but doesnt extract them. Works fine on the Ender crafter though.

**Comment by Rseding91** [comment] 2018-12-29 10:43
I looked into this and figured out the cause: when the automation interface finishes crafting a recipe in the table below it, it calls: ```table.setResult(*find new recipe for items in the table now*);``` which ends up being: ```table.setResult(ItemStack.EMPTY);``` That leaves the crafting table with no result.

Then, when the automation interface gets new items it puts them into the attached table using: ```matrix.setInventorySlotContents(slot, stack);``` and in each of the crafting tables they react by calling: ```this.matrix.set(slot, stack);```

```this.matrix``` is a list of ItemStack and just sets the stack at the given slot to the given stack.

It fails to call onCraftMatrixChanged on the parent Container that owns the tile and manages setting 'result' to the new what-does-this-matrix-craft.

When you open the crafting table something calls the "find out what the items in the table make and set result" and then the table has a result again and the automation interface does its thing. No idea why opening the GUI triggers that (I don't think it should - it should always be in reaction to the inventory contents changing).

**Closed** 2018-12-29 21:42 UTC
Labels: 1.12, Bug
